[2024-04-01T11:51:34.879+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data scheduled__2024-04-01T05:00:00+00:00 [queued]>
[2024-04-01T11:51:34.888+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data scheduled__2024-04-01T05:00:00+00:00 [queued]>
[2024-04-01T11:51:34.890+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-01T11:51:34.908+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data> on 2024-04-01 05:00:00+00:00
[2024-04-01T11:51:34.914+0000] {standard_task_runner.py:60} INFO - Started process 149 to run task
[2024-04-01T11:51:34.917+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'get_data', 'scheduled__2024-04-01T05:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmp_fdo5kyj']
[2024-04-01T11:51:34.919+0000] {standard_task_runner.py:88} INFO - Job 131: Subtask get_data
[2024-04-01T11:51:34.955+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.get_data scheduled__2024-04-01T05:00:00+00:00 [running]> on host d7148197e99c
[2024-04-01T11:51:35.019+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T05:00:00+00:00'
[2024-04-01T11:51:35.021+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pages_dag.py", line 23, in _get_data
    pages = requests.get(url=url, allow_redirects=True)
NameError: name 'requests' is not defined
[2024-04-01T11:51:35.029+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=get_data, execution_date=20240401T050000, start_date=20240401T115134, end_date=20240401T115135
[2024-04-01T11:51:35.038+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 131 for task get_data (name 'requests' is not defined; 149)
[2024-04-01T11:51:35.049+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T11:51:35.057+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-01T11:51:35.068+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
