[2024-04-01T11:51:34.484+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data scheduled__2024-04-01T02:00:00+00:00 [queued]>
[2024-04-01T11:51:34.495+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data scheduled__2024-04-01T02:00:00+00:00 [queued]>
[2024-04-01T11:51:34.496+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-01T11:51:34.593+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data> on 2024-04-01 02:00:00+00:00
[2024-04-01T11:51:34.600+0000] {standard_task_runner.py:60} INFO - Started process 144 to run task
[2024-04-01T11:51:34.605+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'get_data', 'scheduled__2024-04-01T02:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmpainwt322']
[2024-04-01T11:51:34.611+0000] {standard_task_runner.py:88} INFO - Job 123: Subtask get_data
[2024-04-01T11:51:34.681+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.get_data scheduled__2024-04-01T02:00:00+00:00 [running]> on host d7148197e99c
[2024-04-01T11:51:34.774+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T02:00:00+00:00'
[2024-04-01T11:51:34.778+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pages_dag.py", line 23, in _get_data
    pages = requests.get(url=url, allow_redirects=True)
NameError: name 'requests' is not defined
[2024-04-01T11:51:34.788+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=get_data, execution_date=20240401T020000, start_date=20240401T115134, end_date=20240401T115134
[2024-04-01T11:51:34.799+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 123 for task get_data (name 'requests' is not defined; 144)
[2024-04-01T11:51:34.819+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T11:51:34.843+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-01T11:51:34.855+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
