[2024-03-31T18:20:53.310+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-03-31T18:20:52.481219+00:00 [queued]>
[2024-03-31T18:20:53.315+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-03-31T18:20:52.481219+00:00 [queued]>
[2024-03-31T18:20:53.315+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-31T18:20:53.323+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data> on 2024-03-31 18:20:52.481219+00:00
[2024-03-31T18:20:53.326+0000] {standard_task_runner.py:60} INFO - Started process 2254 to run task
[2024-03-31T18:20:53.327+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'get_data', 'manual__2024-03-31T18:20:52.481219+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmphoxphbpl']
[2024-03-31T18:20:53.329+0000] {standard_task_runner.py:88} INFO - Job 104: Subtask get_data
[2024-03-31T18:20:53.356+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-03-31T18:20:52.481219+00:00 [running]> on host f8f92d4c9559
[2024-03-31T18:20:53.381+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-31T18:20:53.402+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T18:20:52.481219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-31T18:20:52.481219+00:00'
[2024-03-31T18:20:53.403+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pages_dag.py", line 16, in _get_data
    request.urlretrieve(url, output_path)
NameError: name 'request' is not defined
[2024-03-31T18:20:53.409+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=get_data, execution_date=20240331T182052, start_date=20240331T182053, end_date=20240331T182053
[2024-03-31T18:20:53.417+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 104 for task get_data (name 'request' is not defined; 2254)
[2024-03-31T18:20:53.460+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-31T18:20:53.468+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
