[2024-04-01T11:52:06.570+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-04-01T11:52:05.213436+00:00 [queued]>
[2024-04-01T11:52:06.574+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-04-01T11:52:05.213436+00:00 [queued]>
[2024-04-01T11:52:06.574+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-01T11:52:06.582+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data> on 2024-04-01 11:52:05.213436+00:00
[2024-04-01T11:52:06.586+0000] {standard_task_runner.py:60} INFO - Started process 169 to run task
[2024-04-01T11:52:06.587+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'get_data', 'manual__2024-04-01T11:52:05.213436+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmp2pgzz_vq']
[2024-04-01T11:52:06.589+0000] {standard_task_runner.py:88} INFO - Job 137: Subtask get_data
[2024-04-01T11:52:06.614+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-04-01T11:52:05.213436+00:00 [running]> on host d7148197e99c
[2024-04-01T11:52:06.723+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T11:52:05.213436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T11:52:05.213436+00:00'
[2024-04-01T11:52:06.724+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pages_dag.py", line 23, in _get_data
    pages = requests.get(url=url, allow_redirects=True)
NameError: name 'requests' is not defined
[2024-04-01T11:52:06.748+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=get_data, execution_date=20240401T115205, start_date=20240401T115206, end_date=20240401T115206
[2024-04-01T11:52:06.755+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 137 for task get_data (name 'requests' is not defined; 169)
[2024-04-01T11:52:06.760+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T11:52:06.766+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-01T11:52:06.776+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
