[2024-03-31T16:42:19.743+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-03-31T16:42:18.281891+00:00 [queued]>
[2024-03-31T16:42:19.747+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launches.download_launches manual__2024-03-31T16:42:18.281891+00:00 [queued]>
[2024-03-31T16:42:19.748+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-31T16:42:19.755+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): download_launches> on 2024-03-31 16:42:18.281891+00:00
[2024-03-31T16:42:19.758+0000] {standard_task_runner.py:60} INFO - Started process 233 to run task
[2024-03-31T16:42:19.760+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'download_launches', 'manual__2024-03-31T16:42:18.281891+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/launches_dag.py', '--cfg-path', '/tmp/tmpdca4aivx']
[2024-03-31T16:42:19.761+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask download_launches
[2024-03-31T16:42:19.787+0000] {task_command.py:423} INFO - Running <TaskInstance: download_rocket_launches.download_launches manual__2024-03-31T16:42:18.281891+00:00 [running]> on host f8f92d4c9559
[2024-03-31T16:42:19.823+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_rocket_launches' AIRFLOW_CTX_TASK_ID='download_launches' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T16:42:18.281891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-31T16:42:18.281891+00:00'
[2024-03-31T16:42:19.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T16:42:19.825+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl -o /data/launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2024-03-31T16:42:19.830+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T16:42:19.834+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-31T16:42:19.835+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-31T16:42:20.362+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2024-03-31T16:42:21.911+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to open the file /data/launches.json: No such file or
[2024-03-31T16:42:21.911+0000] {subprocess.py:93} INFO - Warning: directory
[2024-03-31T16:42:21.912+0000] {subprocess.py:93} INFO -   5 24447    5  1360    0     0    655      0  0:00:37  0:00:02  0:00:35  2490
[2024-03-31T16:42:21.912+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2024-03-31T16:42:21.913+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2024-03-31T16:42:21.919+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-03-31T16:42:21.921+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, execution_date=20240331T164218, start_date=20240331T164219, end_date=20240331T164221
[2024-03-31T16:42:21.929+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task download_launches (Bash command failed. The command returned a non-zero exit code 23.; 233)
[2024-03-31T16:42:21.942+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-31T16:42:21.956+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
