[2024-03-31T19:26:51.122+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-03-31T19:26:49.762805+00:00 [queued]>
[2024-03-31T19:26:51.128+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-03-31T19:26:49.762805+00:00 [queued]>
[2024-03-31T19:26:51.132+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-31T19:26:51.146+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data> on 2024-03-31 19:26:49.762805+00:00
[2024-03-31T19:26:51.149+0000] {standard_task_runner.py:60} INFO - Started process 619 to run task
[2024-03-31T19:26:51.151+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'get_data', 'manual__2024-03-31T19:26:49.762805+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmpwf0efcvv']
[2024-03-31T19:26:51.157+0000] {standard_task_runner.py:88} INFO - Job 118: Subtask get_data
[2024-03-31T19:26:51.201+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.get_data manual__2024-03-31T19:26:49.762805+00:00 [running]> on host b34778d2e23f
[2024-03-31T19:26:51.227+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-31T19:26:51.247+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T19:26:49.762805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-31T19:26:49.762805+00:00'
[2024-03-31T19:26:51.729+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pages_dag.py", line 21, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/local/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-03-31T19:26:51.787+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=get_data, execution_date=20240331T192649, start_date=20240331T192651, end_date=20240331T192651
[2024-03-31T19:26:51.795+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 118 for task get_data (HTTP Error 404: Not Found; 619)
[2024-03-31T19:26:51.809+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-31T19:26:51.815+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-03-31T19:26:51.825+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
