[2024-04-01T12:00:37.122+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.write_to_postgres scheduled__2024-04-01T11:00:00+00:00 [queued]>
[2024-04-01T12:00:37.127+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.write_to_postgres scheduled__2024-04-01T11:00:00+00:00 [queued]>
[2024-04-01T12:00:37.127+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-01T12:00:37.134+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): write_to_postgres> on 2024-04-01 11:00:00+00:00
[2024-04-01T12:00:37.138+0000] {standard_task_runner.py:60} INFO - Started process 328 to run task
[2024-04-01T12:00:37.140+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'write_to_postgres', 'scheduled__2024-04-01T11:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmp_x8drl_r']
[2024-04-01T12:00:37.141+0000] {standard_task_runner.py:88} INFO - Job 144: Subtask write_to_postgres
[2024-04-01T12:00:37.166+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.write_to_postgres scheduled__2024-04-01T11:00:00+00:00 [running]> on host d7148197e99c
[2024-04-01T12:00:37.207+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='write_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T11:00:00+00:00'
[2024-04-01T12:00:37.208+0000] {sql.py:276} INFO - Executing: INSERT INTO pageview_counts VALUES ('Apple', 38, '2024-04-01 11:00:00+00:00');
INSERT INTO pageview_counts VALUES ('Facebook', 404, '2024-04-01 11:00:00+00:00');
INSERT INTO pageview_counts VALUES ('Google', 420, '2024-04-01 11:00:00+00:00');
INSERT INTO pageview_counts VALUES ('Microsoft', 114, '2024-04-01 11:00:00+00:00');
INSERT INTO pageview_counts VALUES ('Amazon', 4, '2024-04-01 11:00:00+00:00');
[2024-04-01T12:00:37.213+0000] {base.py:83} INFO - Using connection ID 'my_postgres' for task execution.
[2024-04-01T12:00:37.219+0000] {base.py:83} INFO - Using connection ID 'my_postgres' for task execution.
[2024-04-01T12:00:37.221+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-04-01T12:00:37.226+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=write_to_postgres, execution_date=20240401T110000, start_date=20240401T120037, end_date=20240401T120037
[2024-04-01T12:00:37.232+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 144 for task write_to_postgres (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 328)
[2024-04-01T12:00:37.272+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T12:00:37.283+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
